### ISSUE TITLE
CPU utilization is 100% when crawler runs

### ISSUE THREAD

**Issue by alwaysR9** [xonce/CSpider#13]
I find CPU utilization is 100% On My Laptop:  Ubuntu 14.04, i3-2370M CPU 2.40GHz.
I want to know why CPU utilization is so high, thanks. Maybe it can be optimized.

**Comment by mzer0-yu** [comment]
Thank you for your feed back to CSpider, we will do the bug(if it were) fixing when you give more detail, such like:
1) how many cores does your laptop's CPU have?
2) What's the compiling configuration?
3) Is this case happening to most scenarios or only specific ones?

Noticed you are Chinese, I post he Chinese text below:

感谢你对CSpider的反馈, 请你提供更多的细节来帮助我们修复这个bug(如果它是一个bug):
1) 你的CPU有多少个核心?
2) 编译配置?
3) 这种情况发生在多数场合下, 还是只发生在一些特定的场合?

**Comment by alwaysR9** [comment]
非常抱歉，没有把问题描述清楚。

问题描述：爬虫进程所占的CPU利用率一直维持在100%

1) 机器CPU型号i3-2370M，2个核心，每个核心2.40GHz
2) 编译命令与该项目README文件中的相同
3) 下载线程数和保存线程数均设置为1，即：
            `cs_setopt_threadnum(spider, DOWNLOAD, 1)`
            `cs_setopt_threadnum(spider, SAVE, 1)`
4) 使用的URL是50个美团店家主页(更多的URL，CUP利用率依然是100%)，我将它们罗列出来：

http://bj.meituan.com/shop/1449675
http://bj.meituan.com/shop/1535473
http://bj.meituan.com/shop/40191
http://bj.meituan.com/shop/318
http://bj.meituan.com/shop/4374627
http://bj.meituan.com/shop/6820850
http://bj.meituan.com/shop/282950
http://bj.meituan.com/shop/505584
http://bj.meituan.com/shop/365566
http://bj.meituan.com/shop/5141148
http://bj.meituan.com/shop/85406
http://bj.meituan.com/shop/285630
http://bj.meituan.com/shop/289772
http://bj.meituan.com/shop/2729323
http://bj.meituan.com/shop/624690
http://bj.meituan.com/shop/5331186
http://bj.meituan.com/shop/4461316
http://bj.meituan.com/shop/40998504
http://bj.meituan.com/shop/1500268
http://bj.meituan.com/shop/2368143
http://bj.meituan.com/shop/346746
http://bj.meituan.com/shop/1646681
http://bj.meituan.com/shop/2492709
http://bj.meituan.com/shop/264962
http://bj.meituan.com/shop/40816713
http://bj.meituan.com/shop/312997
http://bj.meituan.com/shop/6918038
http://bj.meituan.com/shop/267168
http://bj.meituan.com/shop/6515450
http://bj.meituan.com/shop/41661910
http://bj.meituan.com/shop/6710673
http://bj.meituan.com/shop/6260994
http://www.meituan.com/shop/2365954
http://www.meituan.com/shop/5662934
http://www.meituan.com/shop/515640
http://www.meituan.com/shop/287796
http://www.meituan.com/shop/299359
http://www.meituan.com/shop/41894482
http://www.meituan.com/shop/5987954
http://www.meituan.com/shop/2583632
http://www.meituan.com/shop/2365906
http://www.meituan.com/shop/41231193
http://www.meituan.com/shop/6725388
http://www.meituan.com/shop/6853310
http://www.meituan.com/shop/40241773
http://www.meituan.com/shop/2494672
http://www.meituan.com/shop/369847
http://www.meituan.com/shop/1467844
http://www.meituan.com/shop/5061085
http://www.meituan.com/shop/41371436

**Comment by luohaha** [comment]
This issue is fixed now. Thank you so much for your feedback!
