### ISSUE TITLE
Getting liburi

### ISSUE THREAD

**Issue by AntonioCS** [xonce/CSpider#2]
Is there any other way to get liburi without having to compile it? (all other libs I can get via apt-get on ubuntu)

**Comment by mitghi** [comment]
I am afraid not.
Compilation won't take long. You can get it from [here](https://github.com/nevali/liburi).

**Comment by AntonioCS** [comment]
Maybe its just me that, does some C programs on the side, so I don't have all the tools they want but they do ask for quite a few things.

From liburi:
> You will need git, automake, autoconf and libtool.

Until now I didn't need any of those things to compile CSpider. All the things needed for CSpiider I could just get from apt-get.

Now I will have to install them in order to get the liburi that I need to compile CSpider.

So please tell me that everyone else has these tools and its just me that doesn't have them.

**Comment by mitghi** [comment]
Sorry for inconvenience. I integrate liburi directly to the project, so it will be solved.

**Comment by mzer0-yu** [comment]
@mitghi @AntonioCS 
I will write a dependent downloader in later January of 2016, which communicates with CSpider via shared memory, and the scenarios are: CSpider pushs the URLs in a queue of shared memory, then another execution the downloader will download pages and cache them.

Separating codes of CSpider and curl costs time, if you are willing to.

**Comment by AntonioCS** [comment]
@mzer0-yu Maybe open an issue with this and not write on something that is not related with what you are saying.

**Comment by mitghi** [comment]
@mzer0-yu That would be great. I created a Milestone and you can add issues about additional features to it.

**Comment by luohaha** [comment]
@mzer0-yu Nice job!

**Comment by luohaha** [comment]
@mitghi I think about we can add @mzer0-yu and @AntonioCS to our team, and give them admin permission.

**Comment by mitghi** [comment]
@luohaha Yes that would be great.

**Comment by AntonioCS** [comment]
@luohaha @mitghi Thanks for the invitation.
Is there some place we can talk? IRC maybe?

@mitghi Regarding the liburi. How long will your solution take to implement? Would it be a good idea to maybe provide a compilation without liburi?

**Comment by mitghi** [comment]
@AntonioCS What a coincidence :D i was going to write you now that it is finished.I created a easy build system and will commit it in minutes. Try it first, if it plays then we think about it . We can use slack. Please write me an email so i can send the invitation to your address.

**Comment by AntonioCS** [comment]
@mitghi That is great because I am unable to compile liburi even after following their steps.
Where is your email?

**Comment by mitghi** [comment]
@AntonioCS -> mitghi at me dot com

**Comment by mitghi** [comment]
@AntonioCS @luohaha @mzer0-yu 
[liburi with modified build](https://github.com/mitghi/liburi) is up. It worked for @AntonioCS .

**Comment by AntonioCS** [comment]
:+1:
